### ISSUE TITLE
How to specify uri for docker client when using ContainerBuilder api

### ISSUE THREAD

**Issue by pandarun** [isen-ng/testcontainers-dotnet#22]
Hello, thank you for you project!

How could I specify docker client uri when using ContainerBuilder api, see DOCKER_HOST below
[gitlab dind](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor)
```
image: docker:stable

 variables:
   # When using dind service we need to instruct docker, to talk with the
   # daemon started inside of the service. The daemon is available with
   # a network connection instead of the default /var/run/docker.sock socket.
   #
   # The 'docker' hostname is the alias of the service container as described at
   # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
   #
   # Note that if you're using Kubernetes executor, the variable should be set to
   # tcp://localhost:2375 because of how Kubernetes executor connects services
   # to the job container
   DOCKER_HOST: tcp://docker:2375/
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
   DOCKER_DRIVER: overlay2

 services:
   - docker:dind

 before_script:
   - docker info

...
```

Thanks in advance!

**Comment by isen-ng** [comment]
Hello!
Thank you for your question.

It seems like this library don't support that yet.
If you like to have a go at this, PRs are welcome.

Otherwise, I'll work on this, this weekend.

**Comment by isen-ng** [comment]
Reference implementation from java:

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L74

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/DockerClientFactory.java#L105

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L30

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/EnvironmentAndSystemPropertyClientProviderStrategy.java#L22

**Comment by isen-ng** [comment]
Released in https://github.com/isen-ng/testcontainers-dotnet/releases/tag/v1.2.0
Give it a few hours for the builds to show up in nuget.

**Comment by pandarun** [comment]
Thank you!
