### ISSUE TITLE
Use local images

### ISSUE THREAD

**Issue by secana** [isen-ng/testcontainers-dotnet#56]
Hi @isen-ng 

I'm trying to use a container image that is only available locally on my PC, but I get the error message ` Docker.DotNet.DockerApiException : Docker API responded with status code=NotFound, response={"message":"pull access denied for imageName, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}`

To reproduce, build a local Docker image with the name `imageName` and run this code:
```csharp
builder.ConfigureDockerImageName("imageName").Build()
```

Is there a possibility to use a local image or do I need to push it to a Docker registry to be usable?

Alternatively: How can I provide login data for private container registry?

**Comment by isen-ng** [comment]
By available only locally, I assume that this is an image you've built locally using `docker build .`. I want to verify that you do not have a local registry running, and installed your image to the local registry.

If the case is that you've built your own image using `docker build`, then I want to check which tag did you tag your build? You'll need to use the same tag when you specify it when using testcontainers.

eg, if you built your image using,

```
docker build . -t imageName:latest
```

then, 

```
builder.ConfigureDockerImageName("imageName:latest").Build()
```

TestContainers will search your local docker before pulling from the internet. If the image exists on your local machine, then it won't attempt to pull at all.



Regarding,

> Alternatively: How can I provide login data for private container registry?

This is currently not possible for this particular repo (I haven't gotten around to writing that code)

**Comment by secana** [comment]
Thx for the fast answer. I did not built with a tag. With the tag it works.
